# Generated by Django 4.1.6 on 2023-02-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getvideos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('thumbnail', models.URLField()),
                ('video_id', models.CharField(max_length=100)),
            ],
        ),
    ]
