# Generated by Django 4.1.6 on 2023-03-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getvideos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getvideos',
            name='video_id',
        ),
    ]
