# Generated by Django 4.1.6 on 2023-02-11 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getvideos', '0002_downloadvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadVideo',
        ),
    ]
