# Generated by Django 4.1.6 on 2023-02-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_videoquality_quality_videoquality_vid_quality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoquality',
            old_name='vid_quality',
            new_name='quality',
        ),
    ]
