# Generated by Django 4.1.6 on 2023-02-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_vid_quality_videoquality_quality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoQuality',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vid_quality',
            field=models.CharField(choices=[('240p', '240p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], default='240p', max_length=5),
        ),
    ]
