# Generated by Django 4.1.6 on 2023-03-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_delete_videoquality_alter_userprofile_vid_quality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profile'},
        ),
    ]
